# Generated by Django 3.2.3 on 2021-06-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210615_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelisting',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.ArticleType'),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.articletype'),
        ),
    ]
